
export interface AnalysisLevel {
  livello: string; 
  prezzo: number;
  motivazione: string;
  sintesiOperativa: string; // Nuova descrizione operativa rapida
  colore: 'rosso' | 'verde' | 'indigo' | 'ambra';
  importanza: number; 
  ruolo: 'WALL' | 'PIVOT' | 'MAGNET' | 'FRICTION' | 'CONFLUENCE' | 'RESONANCE';
  isDayTrade: boolean;
  scadenzaTipo?: string;
  lato: 'CALL' | 'PUT' | 'BOTH' | 'GAMMA_FLIP';
}

export interface DailyOutlook {
  sentiment: string;
  gammaFlipZone: number;
  volatilityExpectation: string;
  summary: string;
}

export interface MarketDataset {
  id: string;
  name: string;
  content: string;
  type: '0DTE' | 'WEEKLY' | 'MONTHLY' | 'OTHER';
  quantMetrics?: QuantMetrics;
}

export interface AnalysisResponse {
  levels: AnalysisLevel[];
  outlook: DailyOutlook;
}

export interface ChatMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

// Types for auto-fetch options data

export interface OptionsMetadata {
  timestamp: string;
  symbol: string;
  source: string;
}

export interface GammaLevel {
  strike: number;
  gamma: number;
  type: 'call' | 'put';
}

export interface OptionLevel {
  strike: number;
  open_interest: number;
  volume: number;
  gamma: number;
  delta: number;
  vega: number;
  theta: number;
}

export interface StructuredLevels {
  spot_price: number;
  call_levels: OptionLevel[];
  put_levels: OptionLevel[];
  gamma_levels: GammaLevel[];
  gamma_flip: number | null;
}

// Types for Python-generated symbols format

export interface OptionData {
  strike: number;
  side: 'CALL' | 'PUT';
  iv: number;
  oi: number;
  vol: number;
}

export interface ExpiryData {
  label: string;
  date: string;
  options: OptionData[];
  quantMetrics?: QuantMetrics;
}

export interface LegacyExpiryContent {
  content: string;
  type: string;
  date: string;
}

// Legacy format for confluence (backward compatibility)
export interface LegacyConfluenceLevel {
  strike: number;
  distance_pct: number;
}

// Legacy format for resonance (backward compatibility)
export interface LegacyResonanceLevel {
  strike: number;
  distance_pct: number;
}

export interface SelectedLevels {
  // Enhanced format: full ConfluenceLevel objects, or legacy format with just strike/distance
  resonance: Array<ResonanceLevel | LegacyResonanceLevel>;
  confluence: Array<ConfluenceLevel | LegacyConfluenceLevel>;
  call_walls: Array<{strike: number; oi: number; expiry: string; actionability?: LevelActionability}>;
  put_walls: Array<{strike: number; oi: number; expiry: string; actionability?: LevelActionability}>;
  gamma_flip: number;
  max_pain: number;
}

// ============================================================================
// AI ANALYSIS TYPES (Generated by GLM-5)
// ============================================================================

/**
 * AI-generated outlook for a symbol
 */
export interface AIOutlook {
  sentiment: 'bullish' | 'bearish' | 'neutral';
  gammaFlipZone: number;
  volatilityExpectation: string;
  summary: string;
}

/**
 * AI-generated level with enhanced metadata
 */
export interface AILevel {
  livello: string;           // Level name (e.g., "GAMMA FLIP CRITICO")
  prezzo: number;            // Price/strike level
  ruolo: 'WALL' | 'PIVOT' | 'MAGNET' | 'FRICTION' | 'CONFLUENCE' | 'RESONANCE';
  importanza: number;        // Importance score 0-100
  sintesiOperativa: string;  // Operational summary
  motivazione?: string;      // Detailed AI explanation/reason
  scadenzaTipo?: string;     // Expiry type (e.g., "0DTE+MONTHLY")
  lato?: 'CALL' | 'PUT' | 'BOTH' | 'GAMMA_FLIP';
}

/**
 * Complete AI analysis for a symbol
 */
export interface AIAnalysis {
  outlook: AIOutlook;
  levels: AILevel[];
}

export interface SymbolData {
  spot: number;
  generated: string;
  /** Up to 3 expiries: 0DTE, WEEKLY, MONTHLY */
  expiries: ExpiryData[];
  legacy?: Record<string, LegacyExpiryContent>;
  selected_levels?: SelectedLevels;
  ai_analysis?: AIAnalysis;
  /** Total GEX data calculated across all expiries (optional for backward compatibility) */
  totalGexData?: TotalGexData;
}

export interface OptionsDataResponse {
  version: string;
  generated: string | null;
  metadata?: OptionsMetadata;
  structured?: StructuredLevels;
  legacy?: string;
  symbols?: Record<string, SymbolData>;
}

export interface CachedData {
  data: OptionsDataResponse;
  timestamp: number;
}

export interface FetchResult {
  success: boolean;
  data?: OptionsDataResponse;
  error?: string;
  fromCache?: boolean;
}

// ============================================================================
// QUANTITATIVE METRICS TYPES
// ============================================================================

/**
 * Gamma exposure data per strike
 */
export interface GEXData {
  strike: number;
  gex: number;  // in billions
  cumulative_gex: number;
}

/**
 * Total GEX data calculated across all expiries
 * Provides aggregate market gamma exposure analysis
 */
export interface TotalGexData {
  /** Total GEX across all expiries in billions */
  total_gex: number;
  /** GEX breakdown by expiry date */
  gex_by_expiry: Array<{
    /** Expiry date string */
    date: string;
    /** GEX for this expiry in billions */
    gex: number;
    /** Relative weight (0-1) of this expiry's contribution */
    weight: number;
  }>;
  /** Sum of positive GEX in billions */
  positive_gex: number;
  /** Sum of negative GEX in billions */
  negative_gex: number;
  /** Estimated gamma flip point across all expiries */
  flip_point: number;
}

/**
 * Volume/Open Interest analysis for unusual activity detection
 */
export interface VolOIAnalysis {
  call_vol_oi_ratio: number;
  put_vol_oi_ratio: number;
  call_unusual_activity: boolean;
  put_unusual_activity: boolean;
}

/**
 * Multiple Put/Call Ratio variants
 */
export interface PutCallRatios {
  oi_based: number;
  volume_based: number;
  weighted: number;
  delta_adjusted: number;
}

/**
 * Volatility skew analysis for sentiment indication
 */
export interface VolatilitySkew {
  put_iv_avg: number;
  call_iv_avg: number;
  skew_ratio: number;
  skew_type: 'smirk' | 'reverse_smirk' | 'flat';
  sentiment: 'bearish' | 'bullish' | 'neutral';
}

/**
 * Comprehensive quantitative metrics for options analysis
 */
export interface QuantMetrics {
  gamma_flip: number;
  total_gex: number;
  max_pain: number;
  put_call_ratios: PutCallRatios;
  volatility_skew: VolatilitySkew;
  gex_by_strike: GEXData[];
}

// ============================================================================
// MARKET REGIME & CONTEXT TYPES
// ============================================================================

/**
 * Market regime detected by the Python backend using GEX, gamma flip, VIX, and PCR signals.
 * Computed per-symbol by detect_market_regime().
 */
export interface MarketRegime {
  /** Current market regime classification */
  regime: 'trending_up' | 'trending_down' | 'range_bound' | 'volatile';
  /** Confidence of the regime classification (0.0-1.0) */
  confidence: number;
  /** Individual signal scores per regime */
  signals: Record<string, number>;
  /** Individual indicator values used for classification */
  indicators: Record<string, unknown>;
  /** Human-readable interpretation of the regime */
  interpretation: string;
}

/**
 * Dynamic tolerances calibrated to VIX level.
 * Computed by calculate_dynamic_tolerances() in the Python backend.
 */
export interface DynamicTolerances {
  /** Resonance tolerance as decimal fraction (e.g., 0.005 = 0.5%) */
  resonance: number;
  /** Confluence tolerance as decimal fraction (e.g., 0.01 = 1.0%) */
  confluence: number;
  /** Wall proximity tolerance as decimal fraction (e.g., 0.01 = 1.0%) */
  wall_proximity: number;
  /** VIX value used for calculation, or null if unavailable */
  vix: number | null;
  /** Scale factor applied (0.7 at VIX 12, 1.0 at VIX 20, 1.5 at VIX 40) */
  scale: number;
}

/**
 * Complete market context for AI prompt enhancement.
 * Combines regime, tolerances, and timestamp into a single object
 * that can be passed through the AI service chain.
 */
export interface MarketContext {
  /** Market regime data (per-symbol) */
  regime?: MarketRegime;
  /** Dynamic tolerances calibrated to VIX */
  tolerances?: DynamicTolerances;
  /** ISO timestamp of the data */
  timestamp?: string;
}

// ============================================================================
// LEVEL ACTIONABILITY TYPES
// ============================================================================

/**
 * Actionable trading metadata for a level.
 * Computed in Python by assign_actionability() based on level type, market regime, and spot price.
 */
export interface LevelActionability {
  expected_behavior: 'bounce' | 'break' | 'magnet' | 'pin';
  confidence: number;
  confirmation_signals: string[];
  invalidation_level: number;
  invalidation_description: string;
  time_decay_impact: {
    morning: 'strong' | 'moderate' | 'weak' | 'very_strong';
    midday: 'strong' | 'moderate' | 'weak' | 'very_strong';
    afternoon: 'strong' | 'moderate' | 'weak' | 'very_strong';
    note: string;
  } | null;
  trading_priority: 'primary' | 'secondary' | 'contextual';
}

// ============================================================================
// ENHANCED CONFLUENCE LEVEL TYPES
// ============================================================================

/**
 * Per-expiry details at a confluence strike
 */
export interface ConfluenceExpiryDetail {
  expiry_label: string;       // e.g., "0DTE", "WEEKLY"
  call_oi: number;
  put_oi: number;
  call_vol: number;
  put_vol: number;
  call_gamma: number;
  put_gamma: number;
}

/**
 * Enhanced confluence level with detailed metrics
 */
export interface ConfluenceLevel {
  strike: number;
  expiries: string[];          // ["0DTE", "WEEKLY"]
  expiry_label: string;        // "0DTE+WEEKLY"
  total_call_oi: number;
  total_put_oi: number;
  total_call_vol: number;
  total_put_vol: number;
  put_call_ratio: number;
  total_gamma: number;
  expiry_details: ConfluenceExpiryDetail[];
  distance_pct?: number;       // Distance from spot price (optional for backward compat)
  dominantExpiry?: string;     // Expiry with highest weight contributing to this level (e.g., "0DTE")
  actionability?: LevelActionability;
}

/**
 * Enhanced resonance level (same structure as ConfluenceLevel, but with 3 expiries)
 */
export interface ResonanceLevel extends ConfluenceLevel {
  // Same structure as ConfluenceLevel, but expiries will have 3 items
}

// ============================================================================
// TYPE GUARDS FOR ENHANCED LEVELS
// ============================================================================

/**
 * Type guard to check if a confluence level is enhanced (has detailed metrics)
 */
export function isEnhancedConfluenceLevel(
  level: ConfluenceLevel | LegacyConfluenceLevel
): level is ConfluenceLevel {
  return 'expiry_label' in level && 'total_call_oi' in level;
}

/**
 * Type guard to check if a resonance level is enhanced (has detailed metrics)
 */
export function isEnhancedResonanceLevel(
  level: ResonanceLevel | LegacyResonanceLevel
): level is ResonanceLevel {
  return 'expiry_label' in level && 'total_call_oi' in level;
}

// ============================================================================
// AI-READY DATA TYPES (Hybrid AI Approach)
// ============================================================================

/**
 * Strike-level data optimized for AI analysis
 * Aggregated from raw options data
 */
export interface AIReadyStrike {
  strike: number;
  call_oi: number;
  put_oi: number;
  call_vol: number;
  put_vol: number;
  call_iv: number;
  put_iv: number;
  significance_score?: number;  // Computed score for strike importance
}

/**
 * Expiry-level aggregated data for AI analysis
 */
export interface AIReadyExpiry {
  date: string;
  strikes: AIReadyStrike[];
  totals: {
    call_oi: number;
    put_oi: number;
  };
}

/**
 * Complete AI-ready data structure for hybrid AI approach
 * Combines aggregated strike data with pre-calculated metrics
 */
export interface AIReadyData {
  spot: number;
  expiries: Record<string, AIReadyExpiry>;
  precalc_metrics: {
    gamma_flip: number;
    total_gex: number;
    max_pain: number;
  };
}

// ============================================================================
// LEVEL HISTORY TYPES (Evolution Tracking)
// ============================================================================

/**
 * A single key level within a level history snapshot
 */
export interface HistoryKeyLevel {
  strike: number;
  role: string;
  score: number;
  oi: number;
  volume: number;
  expiry: string;
}

/**
 * A snapshot of key levels at a point in time for a symbol
 */
export interface LevelSnapshot {
  timestamp: string;
  spot: number;
  key_levels: HistoryKeyLevel[];
  gamma_flip: number | null;
  total_gex: number | null;
}

/**
 * Complete level history data structure
 * Contains the last N snapshots per symbol
 */
export interface LevelHistory {
  level_history: Record<string, LevelSnapshot[]>;
  last_updated: string;
  max_snapshots: number;
}

/**
 * Evolution trend for a level across snapshots
 */
export interface LevelEvolution {
  trend: 'strengthening' | 'weakening' | 'stable' | 'new';
  scoreChange: number;
  oiChange: number;
  snapshots: number;
}
