
export interface AnalysisLevel {
  livello: string; 
  prezzo: number;
  motivazione: string;
  sintesiOperativa: string; // Nuova descrizione operativa rapida
  colore: 'rosso' | 'verde' | 'indigo' | 'ambra';
  importanza: number; 
  ruolo: 'WALL' | 'PIVOT' | 'MAGNET' | 'FRICTION' | 'CONFLUENCE' | 'RESONANCE';
  isDayTrade: boolean;
  scadenzaTipo?: string;
  lato: 'CALL' | 'PUT' | 'BOTH' | 'GAMMA_FLIP';
}

export interface DailyOutlook {
  sentiment: string;
  gammaFlipZone: number;
  volatilityExpectation: string;
  summary: string;
}

export interface MarketDataset {
  id: string;
  name: string;
  content: string;
  type: '0DTE' | 'WEEKLY' | 'MONTHLY' | 'OTHER';
  quantMetrics?: QuantMetrics;
}

export interface AnalysisResponse {
  levels: AnalysisLevel[];
  outlook: DailyOutlook;
}

export interface ChatMessage {
  role: 'user' | 'model';
  parts: { text: string }[];
}

// Types for auto-fetch options data

export interface OptionsMetadata {
  timestamp: string;
  symbol: string;
  source: string;
}

export interface GammaLevel {
  strike: number;
  gamma: number;
  type: 'call' | 'put';
}

export interface OptionLevel {
  strike: number;
  open_interest: number;
  volume: number;
  gamma: number;
  delta: number;
  vega: number;
  theta: number;
}

export interface StructuredLevels {
  spot_price: number;
  call_levels: OptionLevel[];
  put_levels: OptionLevel[];
  gamma_levels: GammaLevel[];
  gamma_flip: number | null;
}

// Types for Python-generated symbols format

export interface OptionData {
  strike: number;
  side: 'CALL' | 'PUT';
  iv: number;
  oi: number;
  vol: number;
}

export interface ExpiryData {
  label: string;
  date: string;
  options: OptionData[];
  quantMetrics?: QuantMetrics;
}

export interface LegacyExpiryContent {
  content: string;
  type: string;
  date: string;
}

export interface SelectedLevels {
  resonance: Array<{strike: number; distance_pct: number}>;
  confluence: Array<{strike: number; distance_pct: number}>;
  call_walls: Array<{strike: number; oi: number; expiry: string}>;
  put_walls: Array<{strike: number; oi: number; expiry: string}>;
  gamma_flip: number;
  max_pain: number;
}

// ============================================================================
// AI ANALYSIS TYPES (Generated by GLM-5)
// ============================================================================

/**
 * AI-generated outlook for a symbol
 */
export interface AIOutlook {
  sentiment: 'bullish' | 'bearish' | 'neutral';
  gammaFlipZone: number;
  volatilityExpectation: string;
  summary: string;
}

/**
 * AI-generated level with enhanced metadata
 */
export interface AILevel {
  livello: string;           // Level name (e.g., "GAMMA FLIP CRITICO")
  prezzo: number;            // Price/strike level
  ruolo: 'WALL' | 'PIVOT' | 'MAGNET' | 'FRICTION' | 'CONFLUENCE' | 'RESONANCE';
  importanza: number;        // Importance score 0-100
  sintesiOperativa: string;  // Operational summary
  scadenzaTipo?: string;     // Expiry type (e.g., "0DTE+MONTHLY")
  lato?: 'CALL' | 'PUT' | 'BOTH' | 'GAMMA_FLIP';
}

/**
 * Complete AI analysis for a symbol
 */
export interface AIAnalysis {
  outlook: AIOutlook;
  levels: AILevel[];
}

export interface SymbolData {
  spot: number;
  generated: string;
  expiries: ExpiryData[];
  legacy?: Record<string, LegacyExpiryContent>;
  selected_levels?: SelectedLevels;
  ai_analysis?: AIAnalysis;
}

export interface OptionsDataResponse {
  version: string;
  generated: string | null;
  metadata?: OptionsMetadata;
  structured?: StructuredLevels;
  legacy?: string;
  symbols?: Record<string, SymbolData>;
}

export interface CachedData {
  data: OptionsDataResponse;
  timestamp: number;
}

export interface FetchResult {
  success: boolean;
  data?: OptionsDataResponse;
  error?: string;
  fromCache?: boolean;
}

// ============================================================================
// QUANTITATIVE METRICS TYPES
// ============================================================================

/**
 * Gamma exposure data per strike
 */
export interface GEXData {
  strike: number;
  gex: number;  // in billions
  cumulative_gex: number;
}

/**
 * Volume/Open Interest analysis for unusual activity detection
 */
export interface VolOIAnalysis {
  call_vol_oi_ratio: number;
  put_vol_oi_ratio: number;
  call_unusual_activity: boolean;
  put_unusual_activity: boolean;
}

/**
 * Multiple Put/Call Ratio variants
 */
export interface PutCallRatios {
  oi_based: number;
  volume_based: number;
  weighted: number;
  delta_adjusted: number;
}

/**
 * Volatility skew analysis for sentiment indication
 */
export interface VolatilitySkew {
  put_iv_avg: number;
  call_iv_avg: number;
  skew_ratio: number;
  skew_type: 'smirk' | 'reverse_smirk' | 'flat';
  sentiment: 'bearish' | 'bullish' | 'neutral';
}

/**
 * Comprehensive quantitative metrics for options analysis
 */
export interface QuantMetrics {
  gamma_flip: number;
  total_gex: number;
  max_pain: number;
  put_call_ratios: PutCallRatios;
  volatility_skew: VolatilitySkew;
  gex_by_strike: GEXData[];
}
