/**
 * Vercel Data Service
 * 
 * A lightweight data service for the public Vercel site that fetches
 * options data from GitHub Raw URLs instead of calling serverless APIs.
 * 
 * @module services/vercelDataService
 */

import { SymbolData, ExpiryData } from '../types';

// ============================================================================
// CONFIGURATION
// ============================================================================

/**
 * GitHub Raw URL for the options data JSON file.
 * Replace [USER] and [REPO] with actual values when deploying.
 */
const GITHUB_RAW_URL = 'https://raw.githubusercontent.com/pitgian/quant-options-agent/master/data/options_data.json';

/**
 * Cache duration in milliseconds (30 minutes).
 * Data is considered fresh if it was fetched within this window.
 */
const CACHE_DURATION_MS = 30 * 60 * 1000;

// ============================================================================
// INTERFACES
// ============================================================================

/**
 * Structure of the options data served from GitHub Raw.
 * This matches the format generated by the GitHub Actions workflow.
 */
export interface VercelOptionsData {
  /** Version string for the data format */
  version: string;
  /** ISO timestamp when the data was generated */
  generated: string;
  /** Map of symbol names to their options data */
  symbols: {
    [symbol: string]: SymbolData;
  };
}

/**
 * Internal cache structure for storing fetched data.
 */
interface CachedData {
  /** Unix timestamp (ms) when the data was cached */
  timestamp: number;
  /** The cached options data */
  data: VercelOptionsData;
}

// ============================================================================
// MODULE-LEVEL CACHE
// ============================================================================

/**
 * In-memory cache for the fetched options data.
 * This persists for the lifetime of the module.
 */
let cachedData: CachedData | null = null;

// ============================================================================
// MAIN FUNCTIONS
// ============================================================================

/**
 * Fetches options data from GitHub Raw URL with caching.
 * 
 * - Returns cached data if still fresh (< 30 minutes old)
 * - Fetches from GitHub if cache is stale or empty
 * - Falls back to cached data on fetch errors
 * 
 * @returns Promise resolving to VercelOptionsData or null on error
 * 
 * @example
 * ```typescript
 * const data = await fetchVercelOptionsData();
 * if (data) {
 *   console.log('Data generated:', data.generated);
 *   console.log('Available symbols:', Object.keys(data.symbols));
 * }
 * ```
 */
export async function fetchVercelOptionsData(): Promise<VercelOptionsData | null> {
  const now = Date.now();
  
  // Return cached data if still fresh
  if (cachedData && (now - cachedData.timestamp) < CACHE_DURATION_MS) {
    console.log('[vercelDataService] Returning cached data (age:', 
      Math.round((now - cachedData.timestamp) / 1000 / 60), 'minutes)');
    return cachedData.data;
  }
  
  // Fetch fresh data from GitHub Raw
  try {
    console.log('[vercelDataService] Fetching fresh data from GitHub Raw...');
    
    const response = await fetch(GITHUB_RAW_URL, {
      method: 'GET',
      headers: {
        'Accept': 'application/json',
      },
    });
    
    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }
    
    const data: VercelOptionsData = await response.json();
    
    // Validate required fields
    if (!data.version || !data.generated || !data.symbols) {
      throw new Error('Invalid data structure: missing required fields');
    }
    
    // Update cache
    cachedData = {
      timestamp: now,
      data,
    };
    
    console.log('[vercelDataService] Successfully fetched and cached data');
    console.log('[vercelDataService] Version:', data.version, 
      '| Generated:', data.generated, 
      '| Symbols:', Object.keys(data.symbols).join(', '));
    
    return data;
    
  } catch (error) {
    console.error('[vercelDataService] Error fetching data:', error);
    
    // Fall back to stale cached data if available
    if (cachedData) {
      console.warn('[vercelDataService] Falling back to stale cached data');
      return cachedData.data;
    }
    
    return null;
  }
}

/**
 * Retrieves data for a specific symbol from the options data.
 * 
 * @param data - The full options data object
 * @param symbol - The symbol to retrieve (e.g., 'SPY', 'QQQ', 'SPX', 'NDX')
 * @returns SymbolData if found, null otherwise
 * 
 * @example
 * ```typescript
 * const data = await fetchVercelOptionsData();
 * if (data) {
 *   const spyData = getSymbolData(data, 'SPY');
 *   if (spyData) {
 *     console.log('SPY spot price:', spyData.spot);
 *     console.log('Expiries:', spyData.expiries.length);
 *   }
 * }
 * ```
 */
export function getSymbolData(data: VercelOptionsData, symbol: string): SymbolData | null {
  if (!data || !data.symbols) {
    console.warn('[vercelDataService] Invalid data structure');
    return null;
  }
  
  const upperSymbol = symbol.toUpperCase();
  const symbolData = data.symbols[upperSymbol];
  
  if (!symbolData) {
    console.warn(`[vercelDataService] Symbol "${upperSymbol}" not found in data`);
    return null;
  }
  
  return symbolData;
}

/**
 * Checks if the data is fresh (generated less than 30 minutes ago).
 * 
 * @param data - The options data to check
 * @returns true if data is fresh, false otherwise
 * 
 * @example
 * ```typescript
 * const data = await fetchVercelOptionsData();
 * if (data && isDataFresh(data)) {
 *   console.log('Data is up to date');
 * } else {
 *   console.warn('Data may be stale');
 * }
 * ```
 */
export function isDataFresh(data: VercelOptionsData): boolean {
  if (!data || !data.generated) {
    return false;
  }
  
  try {
    const generatedTime = new Date(data.generated).getTime();
    const now = Date.now();
    const ageMs = now - generatedTime;
    
    return ageMs < CACHE_DURATION_MS;
  } catch (error) {
    console.error('[vercelDataService] Error parsing generated timestamp:', error);
    return false;
  }
}

/**
 * Returns a human-readable formatted timestamp of when the data was last updated.
 * 
 * @param data - The options data
 * @returns Formatted string (e.g., "2024-01-15 14:30:00 UTC") or "Unknown" on error
 * 
 * @example
 * ```typescript
 * const data = await fetchVercelOptionsData();
 * if (data) {
 *   console.log('Last update:', getLastUpdateTime(data));
 *   // Output: "Last update: 2024-01-15 14:30:00 UTC"
 * }
 * ```
 */
export function getLastUpdateTime(data: VercelOptionsData): string {
  if (!data || !data.generated) {
    return 'Unknown';
  }
  
  try {
    const date = new Date(data.generated);
    
    // Format in user's local timezone with timezone indication
    const options: Intl.DateTimeFormatOptions = {
      year: 'numeric',
      month: '2-digit',
      day: '2-digit',
      hour: '2-digit',
      minute: '2-digit',
      second: '2-digit',
      hour12: false,
      timeZoneName: 'short'
    };
    
    return date.toLocaleString('it-IT', options);
  } catch (error) {
    console.error('[vercelDataService] Error formatting timestamp:', error);
    return 'Unknown';
  }
}

// ============================================================================
// UTILITY FUNCTIONS
// ============================================================================

/**
 * Gets the age of the data in minutes.
 * 
 * @param data - The options data
 * @returns Age in minutes, or -1 on error
 */
export function getDataAgeMinutes(data: VercelOptionsData): number {
  if (!data || !data.generated) {
    return -1;
  }
  
  try {
    const generatedTime = new Date(data.generated).getTime();
    const now = Date.now();
    const ageMinutes = Math.floor((now - generatedTime) / (1000 * 60));
    return Math.max(0, ageMinutes); // Ensure non-negative
  } catch {
    return -1;
  }
}

/**
 * Returns all available symbols in the data.
 * 
 * @param data - The options data
 * @returns Array of symbol names, or empty array if no data
 */
export function getAvailableSymbols(data: VercelOptionsData | null): string[] {
  if (!data || !data.symbols) {
    return [];
  }
  return Object.keys(data.symbols);
}

/**
 * Clears the in-memory cache.
 * Useful for testing or forcing a fresh fetch.
 */
export function clearCache(): void {
  cachedData = null;
  console.log('[vercelDataService] Cache cleared');
}

/**
 * Gets the current cache status for debugging.
 * 
 * @returns Object with cache info or null if not cached
 */
export function getCacheStatus(): { timestamp: number; ageMinutes: number; symbols: string[] } | null {
  if (!cachedData) {
    return null;
  }
  
  return {
    timestamp: cachedData.timestamp,
    ageMinutes: Math.round((Date.now() - cachedData.timestamp) / 1000 / 60),
    symbols: Object.keys(cachedData.data.symbols),
  };
}
