/**
 * useOptionsData — Custom hook for unified market options data management
 *
 * Handles: market selection (S&P 500 / Nasdaq 100), parallel data fetching for Index + ETF,
 * auto-refresh, loading/error states, and expiry filtering.
 *
 * @module hooks/useOptionsData
 */

import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { DayTradingData, ExpiryFilter, KronosForecast } from '../types';
import { fetchOptionsData, FetchResult, getTimeSinceUpdate } from '../services/dataService';

const KRONOS_GITHUB_URL = 'https://raw.githubusercontent.com/pitgian/quant-options-agent/data/data/kronos_forecast.json';
const KRONOS_LOCAL_URL = '/data/kronos_forecast.json';

const getKronosUrl = () => {
  const isDev = import.meta.env.DEV;
  return isDev ? KRONOS_LOCAL_URL : KRONOS_GITHUB_URL;
};

// ============================================================================
// HOOK RETURN TYPE
// ============================================================================

export interface UseOptionsDataReturn {
  /** True during initial load */
  loading: boolean;
  /** Error message string, if any */
  error: string | null;
  /** Currently selected market */
  market: 'SP500' | 'NASDAQ100';
  /** Change the active market */
  setMarket: (market: 'SP500' | 'NASDAQ100') => void;
  /** ETF-specific day trading data */
  etfData: DayTradingData | null;
  /** Index-specific day trading data */
  indexData: DayTradingData | null;
  /** Human-readable time since last data update */
  timeSinceUpdate: string;
  /** True when a manual refresh is in progress */
  refreshing: boolean;
  /** True when a background (silent) refresh is in progress */
  isBackgroundRefreshing: boolean;
  /** True briefly after new data arrives from a background refresh */
  showUpdatedFlash: boolean;
  /** Currently selected expiry filter */
  expiryFilter: ExpiryFilter;
  /** Change the expiry filter */
  setExpiryFilter: (filter: ExpiryFilter) => void;
  /** Trigger a manual (forced) refresh */
  handleRefresh: () => Promise<void>;
  /** Trigger a silent background refresh */
  silentRefresh: () => Promise<void>;
  /** Timestamp of the last successful client-side fetch */
  lastRefreshed: Date | null;
  /** Forecast generated by Kronos AI model */
  kronosForecast: KronosForecast | null;
}

// ============================================================================
// HOOK IMPLEMENTATION
// ============================================================================

export function useOptionsData(): UseOptionsDataReturn {
  const [market, setMarketState] = useState<'SP500' | 'NASDAQ100'>('SP500');
  const [etfData, setEtfData] = useState<DayTradingData | null>(null);
  const [indexData, setIndexData] = useState<DayTradingData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [timeSinceUpdate, setTimeSinceUpdate] = useState<string>('');
  const [refreshing, setRefreshing] = useState(false);
  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null);
  const [showUpdatedFlash, setShowUpdatedFlash] = useState(false);
  const [isBackgroundRefreshing, setIsBackgroundRefreshing] = useState(false);
  const [expiryFilter, setExpiryFilter] = useState<ExpiryFilter>('0dte');
  const [kronosForecast, setKronosForecast] = useState<KronosForecast | null>(null);


  const [liveSpot, setLiveSpot] = useState<{
    SPX: number | null;
    NDX: number | null;
    SPY: number | null;
    QQQ: number | null;
  }>({ SPX: null, NDX: null, SPY: null, QQQ: null });

  // Fetch live spot prices every 15 seconds (runs as free serverless action, no git push)
  useEffect(() => {
    let active = true;
    const fetchLiveSpot = async () => {
      try {
        const response = await fetch('/api-spot');
        if (!response.ok) return;
        const data = await response.json();
        if (data && active) {
          setLiveSpot({
            SPX: data.SPX,
            NDX: data.NDX,
            SPY: data.SPY,
            QQQ: data.QQQ,
          });
        }
      } catch (err) {
        console.error('Failed to fetch live spot prices:', err);
      }
    };

    fetchLiveSpot();
    const intervalId = setInterval(fetchLiveSpot, 15000);

    return () => {
      active = false;
      clearInterval(intervalId);
    };
  }, []);

  const prevTimestampRef = useRef<string | null>(null);
  const marketRef = useRef(market);

  // Keep marketRef in sync for race condition guards
  useEffect(() => {
    marketRef.current = market;
  }, [market]);

  const setMarket = useCallback((newMarket: 'SP500' | 'NASDAQ100') => {
    setMarketState(newMarket);
    setExpiryFilter('0dte');
    setEtfData(null);
    setIndexData(null);
    setError(null);
  }, []);

  // ---- Data fetching ----
  const loadData = useCallback(async (forceRefresh = false) => {
    const currentMarket = market;
    setLoading(true);
    setError(null);

    const etfSymbol = currentMarket === 'SP500' ? 'SPY' : 'QQQ';
    const indexSymbol = currentMarket === 'SP500' ? 'SPX' : 'NDX';

    try {
      // Fetch symbols and Kronos forecast in parallel from cache/pipeline/devserver
      const [etfResult, indexResult, kronosRes] = await Promise.all([
        fetchOptionsData(etfSymbol, expiryFilter, forceRefresh),
        fetchOptionsData(indexSymbol, expiryFilter, forceRefresh),
        fetch(`${getKronosUrl()}?t=${Date.now()}`).catch(() => null)
      ]);

      // GUARD: market may have changed during fetch
      if (currentMarket !== marketRef.current) return;

      if (kronosRes && kronosRes.ok) {
        try {
          const kData = await kronosRes.json();
          setKronosForecast(kData);
        } catch (e) {
          console.error('Failed to parse Kronos forecast:', e);
        }
      }

      if (etfResult.success && etfResult.data && indexResult.success && indexResult.data) {
        setEtfData(etfResult.data);
        setIndexData(indexResult.data);
        prevTimestampRef.current = etfResult.data.timestamp ?? null;
        setLastRefreshed(new Date());
        setError(null);
      } else {
        setError(etfResult.error || indexResult.error || 'Failed to load options data');
      }
    } catch (err) {
      if (currentMarket !== marketRef.current) return;
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      if (currentMarket === marketRef.current) {
        setLoading(false);
      }
    }

    // Update time since (use ETF timestamp as reference)
    const ts = await getTimeSinceUpdate(etfSymbol);
    if (currentMarket !== marketRef.current) return;
    setTimeSinceUpdate(ts);
  }, [market, expiryFilter]);

  // Silent background refresh
  const silentRefresh = useCallback(async () => {
    setIsBackgroundRefreshing(true);
    const currentMarket = market;
    const etfSymbol = currentMarket === 'SP500' ? 'SPY' : 'QQQ';
    const indexSymbol = currentMarket === 'SP500' ? 'SPX' : 'NDX';

    try {
      const [etfResult, indexResult, kronosRes] = await Promise.all([
        fetchOptionsData(etfSymbol, expiryFilter, true),
        fetchOptionsData(indexSymbol, expiryFilter, true),
        fetch(`${getKronosUrl()}?t=${Date.now()}`).catch(() => null)
      ]);

      // GUARD: Only update if market hasn't changed
      if (currentMarket !== marketRef.current) return;

      if (kronosRes && kronosRes.ok) {
        try {
          const kData = await kronosRes.json();
          setKronosForecast(kData);
        } catch (e) {
          console.error('Failed to parse Kronos forecast:', e);
        }
      }

      if (etfResult.success && etfResult.data && indexResult.success && indexResult.data) {
        const prevTimestamp = prevTimestampRef.current;
        const newTimestamp = etfResult.data.timestamp ?? null;

        if (prevTimestamp !== newTimestamp) {
          setEtfData(etfResult.data);
          setIndexData(indexResult.data);
          prevTimestampRef.current = newTimestamp;
          setLastRefreshed(new Date());
          setShowUpdatedFlash(true);
          setTimeout(() => setShowUpdatedFlash(false), 3000);
        }
      }

      const ts = await getTimeSinceUpdate(etfSymbol);
      if (currentMarket !== marketRef.current) return;
      setTimeSinceUpdate(ts);
    } finally {
      setIsBackgroundRefreshing(false);
    }
  }, [market, expiryFilter]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Auto-refresh: 60s during US market hours (13:30-20:00 UTC), 5 min otherwise
  useEffect(() => {
    let timeoutId: ReturnType<typeof setTimeout>;

    const scheduleNext = () => {
      const now = new Date();
      const utcMinutes = now.getUTCHours() * 60 + now.getUTCMinutes();
      const isMarket = utcMinutes >= 13 * 60 + 30 && utcMinutes <= 20 * 60;
      const delay = isMarket ? 60 * 1000 : 5 * 60 * 1000;

      timeoutId = setTimeout(() => {
        silentRefresh();
        scheduleNext();
      }, delay);
    };

    scheduleNext();
    return () => clearTimeout(timeoutId);
  }, [silentRefresh]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await loadData(true);
    setRefreshing(false);
  };

  // Overridden etfData and indexData with live spot prices
  const finalEtfData = useMemo(() => {
    if (!etfData) return null;
    
    const indexSymbol = market === 'SP500' ? 'SPX' : 'NDX';
    const etfSymbol = market === 'SP500' ? 'SPY' : 'QQQ';
    
    const liveIndexPrice = liveSpot[indexSymbol as keyof typeof liveSpot];
    let livePrice: number | null = null;
    
    if (liveIndexPrice && indexData && indexData.spot && etfData.spot) {
      const ratio = indexData.spot / etfData.spot;
      livePrice = Number((liveIndexPrice / ratio).toFixed(2));
    } else {
      livePrice = liveSpot[etfSymbol as keyof typeof liveSpot];
    }
    
    if (!livePrice) return etfData;
    const finalPrice = livePrice;

    // Keep GEX regime in sync with new price and pre-calculated flip point
    const flipPoint = etfData.gexRegime.flipPoint;
    let regime = etfData.gexRegime.regime;
    let label = etfData.gexRegime.label;
    if (flipPoint !== null) {
      if (finalPrice >= flipPoint) {
        regime = 'positive';
        label = 'Low Volatility';
      } else {
        regime = 'negative';
        label = 'High Volatility';
      }
    }

    return {
      ...etfData,
      spot: finalPrice,
      gexRegime: {
        ...etfData.gexRegime,
        regime,
        label,
      },
      resistance: etfData.resistance.map(r => ({
        ...r,
        distance: Math.round((Math.abs(r.strike - finalPrice) / finalPrice) * 10000) / 100
      })),
      support: etfData.support.map(s => ({
        ...s,
        distance: Math.round((Math.abs(s.strike - finalPrice) / finalPrice) * 10000) / 100
      }))
    };
  }, [etfData, indexData, liveSpot, market]);

  const finalIndexData = useMemo(() => {
    if (!indexData) return null;
    const indexSymbol = market === 'SP500' ? 'SPX' : 'NDX';
    const livePrice = liveSpot[indexSymbol as keyof typeof liveSpot];
    if (!livePrice) return indexData;

    // Keep GEX regime in sync with new price and pre-calculated flip point
    const flipPoint = indexData.gexRegime.flipPoint;
    let regime = indexData.gexRegime.regime;
    let label = indexData.gexRegime.label;
    if (flipPoint !== null) {
      if (livePrice >= flipPoint) {
        regime = 'positive';
        label = 'Low Volatility';
      } else {
        regime = 'negative';
        label = 'High Volatility';
      }
    }

    return {
      ...indexData,
      spot: livePrice,
      gexRegime: {
        ...indexData.gexRegime,
        regime,
        label,
      },
      resistance: indexData.resistance.map(r => ({
        ...r,
        distance: Math.round((Math.abs(r.strike - livePrice) / livePrice) * 10000) / 100
      })),
      support: indexData.support.map(s => ({
        ...s,
        distance: Math.round((Math.abs(s.strike - livePrice) / livePrice) * 10000) / 100
      }))
    };
  }, [indexData, liveSpot, market]);

  return {
    loading,
    error,
    market,
    setMarket,
    etfData: finalEtfData,
    indexData: finalIndexData,
    timeSinceUpdate,
    refreshing,
    isBackgroundRefreshing,
    showUpdatedFlash,
    expiryFilter,
    setExpiryFilter,
    handleRefresh,
    silentRefresh,
    lastRefreshed,
    kronosForecast,
  };
}
