/**
 * useOptionsData — Custom hook for unified market options data management
 *
 * Handles: market selection (S&P 500 / Nasdaq 100), parallel data fetching for Index + ETF,
 * auto-refresh, loading/error states, and expiry filtering.
 *
 * @module hooks/useOptionsData
 */

import { useState, useEffect, useCallback, useRef, useMemo } from 'react';
import { DayTradingData, ExpiryFilter, KronosForecast } from '../types';
import { fetchOptionsData, FetchResult, getTimeSinceUpdate } from '../services/dataService';

const GIST_USER = import.meta.env.VITE_GIST_USER;
const GIST_ID = import.meta.env.VITE_GIST_ID;

const KRONOS_REPO_URL = 'https://raw.githubusercontent.com/pitgian/quant-options-agent/data/data/kronos_forecast.json';
const KRONOS_GIST_URL = GIST_USER && GIST_ID
  ? `https://gist.githubusercontent.com/${GIST_USER}/${GIST_ID}/raw/kronos_forecast.json`
  : null;

const KRONOS_LOCAL_URL = '/data/kronos_forecast.json';

const fetchKronosForecast = async (): Promise<Response | null> => {
  const now = Date.now();
  const isDev = import.meta.env.DEV;

  // Build the list of URLs to try in order
  const urls: { name: string; url: string | null }[] = [];
  
  if (isDev) {
    urls.push({ name: 'Local File', url: KRONOS_LOCAL_URL });
    if (KRONOS_GIST_URL) urls.push({ name: 'Gist', url: KRONOS_GIST_URL });
    urls.push({ name: 'GitHub Repo Branch', url: KRONOS_REPO_URL });
  } else {
    if (KRONOS_GIST_URL) urls.push({ name: 'Gist', url: KRONOS_GIST_URL });
    urls.push({ name: 'GitHub Repo Branch', url: KRONOS_REPO_URL });
    urls.push({ name: 'Local Static Fallback', url: KRONOS_LOCAL_URL });
  }

  const fetchJson = async (url: string): Promise<KronosForecast> => {
    const response = await fetch(`${url}?t=${Date.now()}`, {
      method: 'GET',
      headers: { 'Accept': 'application/json' },
      cache: 'no-cache',
    });

    if (!response.ok) {
      throw new Error(`HTTP ${response.status}: ${response.statusText}`);
    }

    const data: KronosForecast = await response.json();

    if (!data.updated_at || !data.SP500_bias || !data.NASDAQ_bias) {
      throw new Error('Invalid Kronos forecast structure');
    }

    return data;
  };

  let bestData: KronosForecast | null = null;
  let bestTime = 0;

  for (const source of urls) {
    if (!source.url) continue;
    try {
      console.log(`Fetching Kronos forecast from ${source.name}...`);
      const data = await fetchJson(source.url);
      const updateTime = data.updated_at ? new Date(data.updated_at).getTime() : 0;
      
      // Keep track of the newest data we find
      if (!bestData || updateTime > bestTime) {
        bestData = data;
        bestTime = updateTime;
      }
      
      // If the data is fresh (less than 10 minutes old), we can stop searching to speed up loading
      const ageMs = now - updateTime;
      if (ageMs < 10 * 60 * 1000) {
        console.log(`Source ${source.name} is fresh (age: ${Math.round(ageMs / 1000 / 60)}m). Stopping fetch cascade.`);
        break;
      }
    } catch (err) {
      console.warn(`Failed to fetch from ${source.name}:`, err);
    }
  }

  if (bestData) {
    return {
      ok: true,
      json: async () => bestData,
    } as Response;
  }

  return null;
};

// ============================================================================
// HOOK RETURN TYPE
// ============================================================================

export interface UseOptionsDataReturn {
  /** True during initial load */
  loading: boolean;
  /** Error message string, if any */
  error: string | null;
  /** Currently selected market */
  market: 'SP500' | 'NASDAQ100';
  /** Change the active market */
  setMarket: (market: 'SP500' | 'NASDAQ100') => void;
  /** ETF-specific day trading data */
  etfData: DayTradingData | null;
  /** Index-specific day trading data */
  indexData: DayTradingData | null;
  /** Human-readable time since last data update */
  timeSinceUpdate: string;
  /** True when a manual refresh is in progress */
  refreshing: boolean;
  /** True when a background (silent) refresh is in progress */
  isBackgroundRefreshing: boolean;
  /** True briefly after new data arrives from a background refresh */
  showUpdatedFlash: boolean;
  /** Currently selected expiry filter */
  expiryFilter: ExpiryFilter;
  /** Change the expiry filter */
  setExpiryFilter: (filter: ExpiryFilter) => void;
  /** Trigger a manual (forced) refresh */
  handleRefresh: () => Promise<void>;
  /** Trigger a silent background refresh */
  silentRefresh: () => Promise<void>;
  /** Timestamp of the last successful client-side fetch */
  lastRefreshed: Date | null;
  /** Forecast generated by Kronos AI model */
  kronosForecast: KronosForecast | null;
  /** Live spot and futures prices */
  liveSpot: {
    SPX: number | null;
    NDX: number | null;
    SPY: number | null;
    QQQ: number | null;
    ES?: number | null;
    NQ?: number | null;
  };
}

// ============================================================================
// HOOK IMPLEMENTATION
// ============================================================================

export function useOptionsData(): UseOptionsDataReturn {
  const [market, setMarketState] = useState<'SP500' | 'NASDAQ100'>('SP500');
  const [etfData, setEtfData] = useState<DayTradingData | null>(null);
  const [indexData, setIndexData] = useState<DayTradingData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [timeSinceUpdate, setTimeSinceUpdate] = useState<string>('');
  const [refreshing, setRefreshing] = useState(false);
  const [lastRefreshed, setLastRefreshed] = useState<Date | null>(null);
  const [showUpdatedFlash, setShowUpdatedFlash] = useState(false);
  const [isBackgroundRefreshing, setIsBackgroundRefreshing] = useState(false);
  const [expiryFilter, setExpiryFilter] = useState<ExpiryFilter>('0dte');
  const [kronosForecast, setKronosForecast] = useState<KronosForecast | null>(null);


  const [liveSpot, setLiveSpot] = useState<{
    SPX: number | null;
    NDX: number | null;
    SPY: number | null;
    QQQ: number | null;
    ES?: number | null;
    NQ?: number | null;
  }>({ SPX: null, NDX: null, SPY: null, QQQ: null, ES: null, NQ: null });

  // Fetch live spot prices every 15 seconds (runs as free serverless action, no git push)
  useEffect(() => {
    let active = true;
    const fetchLiveSpot = async () => {
      try {
        const response = await fetch(`/api-spot?t=${Date.now()}`, {
          cache: 'no-store'
        });
        if (!response.ok) return;
        const data = await response.json();
        if (data && active) {
          setLiveSpot({
            SPX: data.SPX,
            NDX: data.NDX,
            SPY: data.SPY,
            QQQ: data.QQQ,
            ES: data.ES,
            NQ: data.NQ,
          });
        }
      } catch (err) {
        console.error('Failed to fetch live spot prices:', err);
      }
    };

    fetchLiveSpot();
    const intervalId = setInterval(fetchLiveSpot, 15000);

    return () => {
      active = false;
      clearInterval(intervalId);
    };
  }, []);

  const prevTimestampRef = useRef<string | null>(null);
  const marketRef = useRef(market);

  // Keep marketRef in sync for race condition guards
  useEffect(() => {
    marketRef.current = market;
  }, [market]);

  const setMarket = useCallback((newMarket: 'SP500' | 'NASDAQ100') => {
    setMarketState(newMarket);
    setExpiryFilter('0dte');
    setEtfData(null);
    setIndexData(null);
    setError(null);
  }, []);

  // ---- Data fetching ----
  const loadData = useCallback(async (forceRefresh = false) => {
    const currentMarket = market;
    setLoading(true);
    setError(null);

    const etfSymbol = currentMarket === 'SP500' ? 'SPY' : 'QQQ';
    const indexSymbol = currentMarket === 'SP500' ? 'SPX' : 'NDX';

    try {
      // Fetch symbols and Kronos forecast in parallel from cache/pipeline/devserver
      const [etfResult, indexResult, kronosRes] = await Promise.all([
        fetchOptionsData(etfSymbol, expiryFilter, forceRefresh),
        fetchOptionsData(indexSymbol, expiryFilter, forceRefresh),
        fetchKronosForecast()
      ]);

      // GUARD: market may have changed during fetch
      if (currentMarket !== marketRef.current) return;

      if (kronosRes && kronosRes.ok) {
        try {
          const kData = await kronosRes.json();
          setKronosForecast(kData);
        } catch (e) {
          console.error('Failed to parse Kronos forecast:', e);
        }
      }

      if (etfResult.success && etfResult.data && indexResult.success && indexResult.data) {
        setEtfData(etfResult.data);
        setIndexData(indexResult.data);
        prevTimestampRef.current = etfResult.data.timestamp ?? null;
        setLastRefreshed(new Date());
        setError(null);
      } else {
        setError(etfResult.error || indexResult.error || 'Failed to load options data');
      }
    } catch (err) {
      if (currentMarket !== marketRef.current) return;
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      if (currentMarket === marketRef.current) {
        setLoading(false);
      }
    }

    // Update time since (use ETF timestamp as reference)
    const ts = await getTimeSinceUpdate(etfSymbol);
    if (currentMarket !== marketRef.current) return;
    setTimeSinceUpdate(ts);
  }, [market, expiryFilter]);

  // Silent background refresh
  const silentRefresh = useCallback(async () => {
    setIsBackgroundRefreshing(true);
    const currentMarket = market;
    const etfSymbol = currentMarket === 'SP500' ? 'SPY' : 'QQQ';
    const indexSymbol = currentMarket === 'SP500' ? 'SPX' : 'NDX';

    try {
      const [etfResult, indexResult, kronosRes] = await Promise.all([
        fetchOptionsData(etfSymbol, expiryFilter, true),
        fetchOptionsData(indexSymbol, expiryFilter, true),
        fetchKronosForecast()
      ]);

      // GUARD: Only update if market hasn't changed
      if (currentMarket !== marketRef.current) return;

      if (kronosRes && kronosRes.ok) {
        try {
          const kData = await kronosRes.json();
          setKronosForecast(kData);
        } catch (e) {
          console.error('Failed to parse Kronos forecast:', e);
        }
      }

      if (etfResult.success && etfResult.data && indexResult.success && indexResult.data) {
        const prevTimestamp = prevTimestampRef.current;
        const newTimestamp = etfResult.data.timestamp ?? null;

        if (prevTimestamp !== newTimestamp) {
          setEtfData(etfResult.data);
          setIndexData(indexResult.data);
          prevTimestampRef.current = newTimestamp;
          setLastRefreshed(new Date());
          setShowUpdatedFlash(true);
          setTimeout(() => setShowUpdatedFlash(false), 3000);
        }
      }

      const ts = await getTimeSinceUpdate(etfSymbol);
      if (currentMarket !== marketRef.current) return;
      setTimeSinceUpdate(ts);
    } finally {
      setIsBackgroundRefreshing(false);
    }
  }, [market, expiryFilter]);

  useEffect(() => {
    loadData();
  }, [loadData]);

  // Auto-refresh: 60s during US market hours (13:30-20:00 UTC), 5 min otherwise
  useEffect(() => {
    let timeoutId: ReturnType<typeof setTimeout>;

    const scheduleNext = () => {
      const now = new Date();
      const utcMinutes = now.getUTCHours() * 60 + now.getUTCMinutes();
      const isMarket = utcMinutes >= 13 * 60 + 30 && utcMinutes <= 20 * 60;
      const delay = isMarket ? 60 * 1000 : 5 * 60 * 1000;

      timeoutId = setTimeout(() => {
        silentRefresh();
        scheduleNext();
      }, delay);
    };

    scheduleNext();
    return () => clearTimeout(timeoutId);
  }, [silentRefresh]);

  const handleRefresh = async () => {
    setRefreshing(true);
    await loadData(true);
    setRefreshing(false);
  };

  // Overridden etfData and indexData with live spot prices
  const finalEtfData = useMemo(() => {
    if (!etfData) return null;
    
    const etfSymbol = market === 'SP500' ? 'SPY' : 'QQQ';
    
    // Strictly rely on the cleanly derived ETF spot price calculated by the backend
    const livePrice = liveSpot[etfSymbol as keyof typeof liveSpot];
    if (!livePrice) return etfData;
    const finalPrice = livePrice;

    // Use Cash ETF price for GEX regime detection to match options contract settlement
    const cashPrice = liveSpot[etfSymbol as keyof typeof liveSpot] || etfData.spot;
    const flipPoint = etfData.gexRegime.flipPoint;
    let regime = etfData.gexRegime.regime;
    let label = etfData.gexRegime.label;
    if (flipPoint !== null) {
      if (cashPrice >= flipPoint) {
        regime = 'positive';
        label = 'Low Volatility';
      } else {
        regime = 'negative';
        label = 'High Volatility';
      }
    }

    return {
      ...etfData,
      spot: finalPrice,
      gexRegime: {
        ...etfData.gexRegime,
        regime,
        label,
      },
      resistance: etfData.resistance.map(r => ({
        ...r,
        distance: Math.round((Math.abs(r.strike - finalPrice) / finalPrice) * 10000) / 100
      })),
      support: etfData.support.map(s => ({
        ...s,
        distance: Math.round((Math.abs(s.strike - finalPrice) / finalPrice) * 10000) / 100
      }))
    };
  }, [etfData, indexData, liveSpot, market]);

  const finalIndexData = useMemo(() => {
    if (!indexData) return null;
    const indexSymbol = market === 'SP500' ? 'SPX' : 'NDX';

    // Strictly rely on the cleanly derived Cash index spot price calculated by the backend
    const livePrice = liveSpot[indexSymbol as keyof typeof liveSpot];
    if (!livePrice) return indexData;

    // Use Cash Index price for GEX regime detection to match options contract settlement
    const cashPrice = liveSpot[indexSymbol as keyof typeof liveSpot] || indexData.spot;
    const flipPoint = indexData.gexRegime.flipPoint;
    let regime = indexData.gexRegime.regime;
    let label = indexData.gexRegime.label;
    if (flipPoint !== null) {
      if (cashPrice >= flipPoint) {
        regime = 'positive';
        label = 'Low Volatility';
      } else {
        regime = 'negative';
        label = 'High Volatility';
      }
    }

    return {
      ...indexData,
      spot: livePrice,
      gexRegime: {
        ...indexData.gexRegime,
        regime,
        label,
      },
      resistance: indexData.resistance.map(r => ({
        ...r,
        distance: Math.round((Math.abs(r.strike - livePrice) / livePrice) * 10000) / 100
      })),
      support: indexData.support.map(s => ({
        ...s,
        distance: Math.round((Math.abs(s.strike - livePrice) / livePrice) * 10000) / 100
      }))
    };
  }, [indexData, liveSpot, market]);

  return {
    loading,
    error,
    market,
    setMarket,
    etfData: finalEtfData,
    indexData: finalIndexData,
    timeSinceUpdate,
    refreshing,
    isBackgroundRefreshing,
    showUpdatedFlash,
    expiryFilter,
    setExpiryFilter,
    handleRefresh,
    silentRefresh,
    lastRefreshed,
    kronosForecast,
    liveSpot,
  };
}
