#!/usr/bin/env python3
"""
Generate parity fixtures for the Python <-> TypeScript quantitative logic.

Outputs a JSON file at scripts/test/parity_fixtures.json containing concrete
inputs and the Python-computed outputs for:

  - estimate_gamma     (Black-Scholes gamma)
  - gex_per_strike     (per-strike GEX aggregation, including time decay)
  - wall_dte_weights   (DTE-dependent OI/Vol weighting used by wall scoring)

The TypeScript test suite (services/*.parity.test.ts) consumes this file and
checks that the TS implementations produce the same numbers. If the two sides
diverge, `npm test` breaks — surfacing the drift instead of letting it silently
produce inconsistent dashboards.

Usage:
    .venv/bin/python scripts/test/generate_parity_fixtures.py
"""
import importlib.util
import json
import os
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
SCRIPT = ROOT / "scripts" / "fetch_options_data.py"
OUT = HERE / "parity_fixtures.json"


def load_fod_module():
    spec = importlib.util.spec_from_file_location("fod", str(SCRIPT))
    m = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(m)
    return m


def gen_gamma_cases(mod):
    """Black-Scholes gamma across a representative grid."""
    cases = []
    for spot in [400, 500, 600]:
        for strike_offset in [-30, -10, 0, 10, 30]:
            strike = spot + strike_offset
            for dte in [1, 7, 30]:
                for iv in [0.10, 0.20, 0.40]:
                    gamma = mod.estimate_gamma(
                        spot=float(spot), strike=float(strike),
                        dte=dte, symbol="SPY", implied_vol=iv,
                    )
                    cases.append({
                        "spot": spot, "strike": strike, "dte": dte,
                        "symbol": "SPY", "implied_vol": iv,
                        "expected_gamma": gamma,
                    })
    return cases


def gen_gex_cases(mod):
    """
    Per-strike GEX for a simple synthetic chain, computed with the SAME formula
    used in fetch_symbol_data():
        gex = oi * gamma * CONTRACT_SIZE(=100) * spot^2 * sign * time_weight
        time_weight = 1 / (1 + dte/7)
        sign = +1 calls, -1 puts
    """
    CONTRACT_SIZE = 100
    spot = 500.0

    # Synthetic options: (strike, side, oi, gamma, dte)
    options = [
        (495, "PUT",  1000, None, 0),
        (495, "CALL",  500,  None, 0),
        (505, "CALL", 800,  None, 7),
        (500, "PUT",  300,  None, 30),
    ]

    cases = []
    for strike, side, oi, gamma_in, dte in options:
        gamma = gamma_in if gamma_in is not None else mod.estimate_gamma(
            spot=spot, strike=float(strike), dte=dte, symbol="SPY", implied_vol=0.15,
        )
        sign = 1 if side == "CALL" else -1
        time_weight = 1.0 / (1.0 + dte / 7.0)
        gex = oi * gamma * CONTRACT_SIZE * spot * spot * sign * time_weight
        cases.append({
            "strike": strike, "side": side, "oi": oi, "dte": dte,
            "gamma": gamma, "sign": sign, "time_weight": time_weight,
            "expected_gex": gex,
        })
    return cases


def gen_dte_weight_cases():
    """
    DTE-dependent OI/Vol weights shared by Python _score_and_rank and
    TS wallService.computeWalls:
        dte == 0 -> 0.25 / 0.75
        dte <= 3 -> 0.50 / 0.50
        else     -> 0.70 / 0.30
    """
    cases = []
    for dte, (oi_w, vol_w) in [(0, (0.25, 0.75)), (3, (0.50, 0.50)), (30, (0.70, 0.30))]:
        cases.append({"dte": dte, "expected_oi_weight": oi_w, "expected_vol_weight": vol_w})
    return cases


def main():
    mod = load_fod_module()
    fixtures = {
        "_description": "Parity fixtures generated by Python. Consumed by TS tests to verify both sides agree.",
        "_generated_by": "scripts/test/generate_parity_fixtures.py",
        "_source": "scripts/fetch_options_data.py",
        "gamma_cases": gen_gamma_cases(mod),
        "gex_cases": gen_gex_cases(mod),
        "dte_weight_cases": gen_dte_weight_cases(),
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(fixtures, f, indent=2)
    print(f"Wrote {len(fixtures['gamma_cases'])} gamma cases, "
          f"{len(fixtures['gex_cases'])} GEX cases, "
          f"{len(fixtures['dte_weight_cases'])} DTE-weight cases")
    print(f"  -> {OUT}")


if __name__ == "__main__":
    main()
