/**
 * Vercel Serverless API (Simplified)
 *
 * Serves as a health check and data proxy for the options analysis app.
 * All options data is pre-generated by the GitHub Actions workflow and
 * served as a static JSON file from /data/options_data.json.
 *
 * @module api/index
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';
import { fetchSpotPrices } from '../lib/spotPrices';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  // Only allow GET
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Handle live spot prices request
  if (req.query.action === 'spot') {
    try {
      const spotData = await fetchSpotPrices();
      res.setHeader('Cache-Control', 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0');
      return res.status(200).json(spotData);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to fetch spot prices', details: String(error) });
    }
  }

  // Health check / status endpoint
  return res.status(200).json({
    status: 'ok',
    service: 'options-wall-analyzer',
    timestamp: new Date().toISOString(),
    dataUrl: '/data/options_data.json',
  });
}
