/**
 * Vercel Serverless API (Simplified)
 *
 * Serves as a health check and data proxy for the options analysis app.
 * All options data is pre-generated by the GitHub Actions workflow and
 * served as a static JSON file from /data/options_data.json.
 *
 * @module api/index
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  // Only allow GET
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Handle live spot prices request
  if (req.query.action === 'spot') {
    try {
      // Fetch SPY, QQQ, ES=F, NQ=F, ^SPX, and ^NDX quotes in parallel
      const symbols = ['SPY', 'QQQ', 'ES=F', 'NQ=F', '^SPX', '^NDX'];
      const quotes: Record<string, { live: number | null; prevClose: number | null }> = {};

      await Promise.all(
        symbols.map(async (symbol) => {
          try {
            const response = await fetch(
              `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1m&range=1d&includePrePost=true`,
              {
                headers: {
                  'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
                }
              }
            );
            if (!response.ok) throw new Error(`HTTP ${response.status}`);
            const data = (await response.json()) as any;
            const result = data?.chart?.result?.[0];
            const meta = result?.meta;
            const closes = result?.indicators?.quote?.[0]?.close || [];
            
            let lastCandlePrice = null;
            for (let i = closes.length - 1; i >= 0; i--) {
              if (closes[i] !== null && closes[i] !== undefined) {
                lastCandlePrice = closes[i];
                break;
              }
            }
            
            const live = meta?.regularMarketPrice || lastCandlePrice;
            const prevClose = meta?.chartPreviousClose || meta?.previousClose || lastCandlePrice;
            
            quotes[symbol] = { live, prevClose };
          } catch (err) {
            console.error(`Error fetching ${symbol}:`, err);
            quotes[symbol] = { live: null, prevClose: null };
          }
        })
      );

      // Extract variables with defaults
      const spyPrev = quotes['SPY']?.prevClose || null;
      const qqqPrev = quotes['QQQ']?.prevClose || null;
      
      const esLive = quotes['ES=F']?.live || null;
      const esPrev = quotes['ES=F']?.prevClose || null;
      
      const nqLive = quotes['NQ=F']?.live || null;
      const nqPrev = quotes['NQ=F']?.prevClose || null;
      
      const spxPrev = quotes['^SPX']?.prevClose || null;
      const ndxPrev = quotes['^NDX']?.prevClose || null;

      // Always derive spot prices from active futures returns 24/5
      const esRatio = (esLive && esPrev) ? (esLive / esPrev) : 1.0;
      const nqRatio = (nqLive && nqPrev) ? (nqLive / nqPrev) : 1.0;
      
      const derivedSPX = spxPrev ? Number((spxPrev * esRatio).toFixed(2)) : null;
      const derivedNDX = ndxPrev ? Number((ndxPrev * nqRatio).toFixed(2)) : null;
      const derivedSPY = spyPrev ? Number((spyPrev * esRatio).toFixed(2)) : null;
      const derivedQQQ = qqqPrev ? Number((qqqPrev * nqRatio).toFixed(2)) : null;

      const spotData = {
        SPX: derivedSPX,
        NDX: derivedNDX,
        SPY: derivedSPY,
        QQQ: derivedQQQ,
        ES: esLive,
        NQ: nqLive,
        timestamp: new Date().toISOString()
      };

      return res.status(200).json(spotData);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to fetch spot prices', details: String(error) });
    }
  }

  // Health check / status endpoint
  return res.status(200).json({
    status: 'ok',
    service: 'options-wall-analyzer',
    timestamp: new Date().toISOString(),
    dataUrl: '/data/options_data.json',
  });
}
