/**
 * Vercel Serverless API (Simplified)
 *
 * Serves as a health check and data proxy for the options analysis app.
 * All options data is pre-generated by the GitHub Actions workflow and
 * served as a static JSON file from /data/options_data.json.
 *
 * @module api/index
 */

import type { VercelRequest, VercelResponse } from '@vercel/node';

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS headers
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  // Handle preflight
  if (req.method === 'OPTIONS') {
    return res.status(204).end();
  }

  // Only allow GET
  if (req.method !== 'GET') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  // Handle live spot prices request
  if (req.query.action === 'spot') {
    try {
      const symbols = ['SPY', 'QQQ', '^SPX', '^NDX'];
      const quotes = await Promise.all(
        symbols.map(async (symbol) => {
          try {
            const response = await fetch(`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?interval=1m&range=1d`);
            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);
            const data = await response.json();
            const meta = data?.chart?.result?.[0]?.meta;
            return { symbol, price: meta?.regularMarketPrice || null };
          } catch (err) {
            console.error(`Error fetching ${symbol}:`, err);
            return { symbol, price: null };
          }
        })
      );

      const spotData = {
        SPY: quotes.find(q => q.symbol === 'SPY')?.price || null,
        QQQ: quotes.find(q => q.symbol === 'QQQ')?.price || null,
        SPX: quotes.find(q => q.symbol === '^SPX')?.price || null,
        NDX: quotes.find(q => q.symbol === '^NDX')?.price || null,
        timestamp: new Date().toISOString()
      };

      return res.status(200).json(spotData);
    } catch (error) {
      return res.status(500).json({ error: 'Failed to fetch spot prices', details: String(error) });
    }
  }

  // Health check / status endpoint
  return res.status(200).json({
    status: 'ok',
    service: 'options-wall-analyzer',
    timestamp: new Date().toISOString(),
    dataUrl: '/data/options_data.json',
  });
}
